### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by eagleoflqj** [otterkit/highlightjs-cobol#1]
Thanks for your project.
Could you please add type support? Currently I have to use `ts-ignore`
https://github.com/LibreService/my_file_type/blob/49060cb96ee1418e79ac28e8e082a3f04805487e/src/components/MyPreviewText.vue#L9-L10

**Comment by KTSnowy** [comment]
Hey @eagleoflqj, sure I'll look into adding typescript support. I'll let you know when I get it working so that you can test it with your project.

**Comment by KTSnowy** [comment]
Hey @eagleoflqj I just made a new release to attempt to fix the types not working. Could you try updating the package and checking if it's working now?

**Comment by eagleoflqj** [comment]
```sh
my_file_type$ npx vue-tsc --noEmit
src/components/MyPreviewText.vue:9:19 - error TS7016: Could not find a declaration file for module 'highlightjs-cobol'. '/mnt/storage/github/my_file_type/node_modules/.pnpm/highlightjs-cobol@0.3.2/node_modules/highlightjs-cobol/src/cobol.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/highlightjs-cobol` if it exists or add a new declaration (.d.ts) file containing `declare module 'highlightjs-cobol';`

9 import cobol from 'highlightjs-cobol'
                    ~~~~~~~~~~~~~~~~~~~


Found 1 error in src/components/MyPreviewText.vue:9
```
It seems not fixed. Maybe we need a `.d.ts` file?

**Comment by KTSnowy** [comment]
> Maybe we need a .d.ts file?

Most likely yeah. The highlight.js package has it's own .d.ts file. Could you try copying it over to the cobol package's folder?

If that fixes it I'll add that file to the repo as well.

**Comment by KTSnowy** [comment]
Hey @eagleoflqj I just made another release (0.3.3) with a d.ts file. Could you check if that fixes it?

**Comment by eagleoflqj** [comment]
It's fixed. Thank you!
